name: ChatOps deploy staging

on:
  issue_comment:
    types: [created]

env:
  ENVIRONMENT: staging

jobs:
  command:
    name: /deploy staging
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy staging')
    steps:
      - name: Add reaction
        uses: actions/github-script@v4
        with:
          script: |
            github.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            })
      - name: Trigger deployment
        uses: actions/github-script@v4
        with:
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
          
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-to-environment.yml',
              ref: pr.data.head.ref,
              inputs: {
                environment: '${{ env.ENVIRONMENT }}'
              }
            })
