name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment which you want to deploy a new version'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Build and Deploy
        run: |
          echo ${{ github.event.inputs.environment }}